const test = require("node:test");
const assert = require("node:assert/strict");
const engine = require("./assessmentEngine.js");
function complete(firstAnswers = {}) { let s = engine.createAssessment(); for (let i = 0; i < 40 && !s.completed; i += 1) { const q = engine.currentQuestion(s); if (!q) break; let answer = firstAnswers[q.id] ?? q.options[0].id; if (q.max > 1) answer = firstAnswers[q.id] || [q.options[0].id]; s = engine.submitAnswer(s, answer); } return s; }
test("normal path produces a reversible non-diagnostic single-event map", () => { const r = engine.buildResult(complete({ NEED_01: "clarify", ENTRY_01: "relationship_change", UNDERSTANDING_01: "yes", REL_02: "no", MEANING_01: "rejected", FEELING_01: "fear", LOOP_01: "reassure" })); assert.equal(r.type, "reflection"); assert.match(r.pathway.trigger, /回应/); assert.match(r.pathway.hypothesis, /可能|仍需/); assert.deepEqual(r.cycle.map((line) => line.split("：")[0]), ["发生的线索", "你的解释", "感受", "做了或没有做", "带来的结果", "待验证猜测", "仍然不知道什么"]); });
test("urgent safety stops ordinary analysis", () => { const r = engine.buildResult(complete({ SAFE_01: "risk", SAFE_02: "yes", SAFE_03: "yes" })); assert.equal(r.type, "SAFE_URGENT"); assert.match(r.action, /紧急服务/); });
test("relationship violence routes to external safety", () => { const r = engine.buildResult(complete({ ENTRY_01: "conflict_boundary", REL_02: "yes" })); assert.equal(r.type, "EXT_SAFE"); });
test("unclear path remains finishable", () => { const r = engine.buildResult(complete({ ENTRY_01: "cannot_recall", FIRST_01: "unclear", EMOTION_01: "skip" })); assert.equal(r.type, "reflection"); assert.match(r.pathway.trigger, /想不起/); });
test("ordinary relationship route stays gradual and includes a correctable understanding", () => { const s = complete({ NEED_01: "clarify", ENTRY_01: "relationship_change", UNDERSTANDING_01: "partly", REL_02: "no", PATTERN_01: "first" }); assert.equal(s.completed, true); assert.equal(s.path.filter((id) => engine.coreQuestions.includes(id)).length, 8); assert.ok(s.path.indexOf("UNDERSTANDING_01") < s.path.indexOf("MEANING_01")); assert.ok(s.path.indexOf("MEANING_01") < s.path.indexOf("FEELING_01")); assert.ok(s.path.indexOf("FEELING_01") < s.path.indexOf("LOOP_01")); assert.equal(s.path.includes("TIME_01"), false); });
test("settling need adds a skippable local grounding step", () => { let s = engine.createAssessment(); s = engine.submitAnswer(s, "continue"); s = engine.submitAnswer(s, "safe"); s = engine.submitAnswer(s, "settle"); assert.equal(engine.currentQuestion(s).id, "GROUND_01"); s = engine.submitAnswer(s, "skip"); assert.equal(engine.currentQuestion(s).id, "ENTRY_01"); });
test("conditional first-reaction branches rejoin at meaning", () => { for (const first of ["body_first", "action_urge", "relationship_feeling", "function_impact"]) { const s = complete({ NEED_01: "clarify", ENTRY_01: "task_evaluation", FIRST_01: first, PATTERN_01: "first" }); assert.equal(s.completed, true, first); assert.equal(s.path.includes("MEANING_01"), true, first); } });
test("repeated problems receive one compact support check", () => { const s = complete({ NEED_01: "next", ENTRY_01: "task_evaluation", FIRST_01: "thought_first", PATTERN_01: "often", SUPPORT_01: "hard" }); const r = engine.buildResult(s); assert.equal(s.path.includes("SUPPORT_01"), true); assert.equal(r.support, "S2 建议专业评估"); });
